name: Run Unit-Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.12
    - name: Install Python dependencies
      run: pip install -e .[test,dev,torch]
    - name: Run Unit test_const
      run: 	python -m pytest -s -v ./tests/unit/test_const.py
    - name: Run Unit test_handler
      run: 	python -m pytest -s -v ./tests/unit/test_handler.py
    - name: Run Unit test_sentence_transformers
      run: 	python -m pytest -s -v ./tests/unit/test_sentence_transformers.py
    - name: Run Unit test_serializer
      run: 	python -m pytest -s -v ./tests/unit/test_serializer.py
    - name: Run Unit test_utils
      run: 	python -m pytest -s -v ./tests/unit/test_utils.py
    # - name: Run Unit Tests
    #   run: make unit test